// (c) Michael Buro 1992-2002, licensed under the GNU Public License, version 2

#ifndef	o_HEADER
#define	o_HEADER

/*
 * o_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `o.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;

extern Xv_opaque	o_menu1_create();

typedef struct {
	Xv_opaque	window;
	Xv_opaque	conButtons;
	Xv_opaque	butZurueck;
	Xv_opaque	butVor;
	Xv_opaque	butOptionen;
	Xv_opaque	butNeu;
	Xv_opaque	butWeiter;
	Xv_opaque	butStop;
	Xv_opaque	message1;
	Xv_opaque	message2;
	Xv_opaque	message3;
	Xv_opaque	message4;
	Xv_opaque	message5;
	Xv_opaque	message6;
	Xv_opaque	message7;
	Xv_opaque	message32;
	Xv_opaque	controls3;
	Xv_opaque	message9;
	Xv_opaque	message10;
	Xv_opaque	message11;
	Xv_opaque	message12;
	Xv_opaque	message13;
	Xv_opaque	message14;
	Xv_opaque	message15;
	Xv_opaque	message16;
	Xv_opaque	canBrett;
	Xv_opaque	controls4;
	Xv_opaque	message17;
	Xv_opaque	message18;
	Xv_opaque	message19;
	Xv_opaque	message20;
	Xv_opaque	message21;
	Xv_opaque	message22;
	Xv_opaque	message23;
	Xv_opaque	message24;
	Xv_opaque	conMsg;
	Xv_opaque	message25;
	Xv_opaque	message26;
	Xv_opaque	message27;
	Xv_opaque	message28;
	Xv_opaque	message29;
	Xv_opaque	message30;
	Xv_opaque	message31;
	Xv_opaque	message33;
	Xv_opaque	message8;
	Xv_opaque	message34;
	Xv_opaque	msgZeitB;
	Xv_opaque	msgSteineB;
	Xv_opaque	msgSteine;
	Xv_opaque	msgSteineW;
	Xv_opaque	msgZeitW;
	Xv_opaque	msgZugB;
	Xv_opaque	msgZugW;
	Xv_opaque	msgBlaBla;
} o_window_objects;

extern o_window_objects	*o_window_objects_initialize();

extern Xv_opaque	o_window_window_create();
extern Xv_opaque	o_window_conButtons_create();
extern Xv_opaque	o_window_butZurueck_create();
extern Xv_opaque	o_window_butVor_create();
extern Xv_opaque	o_window_butOptionen_create();
extern Xv_opaque	o_window_butNeu_create();
extern Xv_opaque	o_window_butWeiter_create();
extern Xv_opaque	o_window_butStop_create();
extern Xv_opaque	o_window_message1_create();
extern Xv_opaque	o_window_message2_create();
extern Xv_opaque	o_window_message3_create();
extern Xv_opaque	o_window_message4_create();
extern Xv_opaque	o_window_message5_create();
extern Xv_opaque	o_window_message6_create();
extern Xv_opaque	o_window_message7_create();
extern Xv_opaque	o_window_message32_create();
extern Xv_opaque	o_window_controls3_create();
extern Xv_opaque	o_window_message9_create();
extern Xv_opaque	o_window_message10_create();
extern Xv_opaque	o_window_message11_create();
extern Xv_opaque	o_window_message12_create();
extern Xv_opaque	o_window_message13_create();
extern Xv_opaque	o_window_message14_create();
extern Xv_opaque	o_window_message15_create();
extern Xv_opaque	o_window_message16_create();
extern Xv_opaque	o_window_canBrett_create();
extern Xv_opaque	o_window_controls4_create();
extern Xv_opaque	o_window_message17_create();
extern Xv_opaque	o_window_message18_create();
extern Xv_opaque	o_window_message19_create();
extern Xv_opaque	o_window_message20_create();
extern Xv_opaque	o_window_message21_create();
extern Xv_opaque	o_window_message22_create();
extern Xv_opaque	o_window_message23_create();
extern Xv_opaque	o_window_message24_create();
extern Xv_opaque	o_window_conMsg_create();
extern Xv_opaque	o_window_message25_create();
extern Xv_opaque	o_window_message26_create();
extern Xv_opaque	o_window_message27_create();
extern Xv_opaque	o_window_message28_create();
extern Xv_opaque	o_window_message29_create();
extern Xv_opaque	o_window_message30_create();
extern Xv_opaque	o_window_message31_create();
extern Xv_opaque	o_window_message33_create();
extern Xv_opaque	o_window_message8_create();
extern Xv_opaque	o_window_message34_create();
extern Xv_opaque	o_window_msgZeitB_create();
extern Xv_opaque	o_window_msgSteineB_create();
extern Xv_opaque	o_window_msgSteine_create();
extern Xv_opaque	o_window_msgSteineW_create();
extern Xv_opaque	o_window_msgZeitW_create();
extern Xv_opaque	o_window_msgZugB_create();
extern Xv_opaque	o_window_msgZugW_create();
extern Xv_opaque	o_window_msgBlaBla_create();

typedef struct {
	Xv_opaque	popEinstellungen;
	Xv_opaque	conEigenschaften;
	Xv_opaque	setSpielerB;
	Xv_opaque	msgFarbe1;
	Xv_opaque	textRestzeitB;
	Xv_opaque	setSpielerW;
	Xv_opaque	msgFarbe2;
	Xv_opaque	textRestzeitW;
	Xv_opaque	butWechseln;
	Xv_opaque	butBenutzen;
	Xv_opaque	setMoegl;
	Xv_opaque	setBeep;
} o_popEinstellungen_objects;

extern o_popEinstellungen_objects	*o_popEinstellungen_objects_initialize();

extern Xv_opaque	o_popEinstellungen_popEinstellungen_create();
extern Xv_opaque	o_popEinstellungen_conEigenschaften_create();
extern Xv_opaque	o_popEinstellungen_setSpielerB_create();
extern Xv_opaque	o_popEinstellungen_msgFarbe1_create();
extern Xv_opaque	o_popEinstellungen_textRestzeitB_create();
extern Xv_opaque	o_popEinstellungen_setSpielerW_create();
extern Xv_opaque	o_popEinstellungen_msgFarbe2_create();
extern Xv_opaque	o_popEinstellungen_textRestzeitW_create();
extern Xv_opaque	o_popEinstellungen_butWechseln_create();
extern Xv_opaque	o_popEinstellungen_butBenutzen_create();
extern Xv_opaque	o_popEinstellungen_setMoegl_create();
extern Xv_opaque	o_popEinstellungen_setBeep_create();

typedef struct {
	Xv_opaque	popEingabe;
	Xv_opaque	controls2;
	Xv_opaque	setAmZug;
	Xv_opaque	setSetzModus;
	Xv_opaque	butDrehen;
	Xv_opaque	butSpiegeln;
	Xv_opaque	butFuellen;
	Xv_opaque	butGrund;
	Xv_opaque	butEingabeOk;
} o_popEingabe_objects;

extern o_popEingabe_objects	*o_popEingabe_objects_initialize();

extern Xv_opaque	o_popEingabe_popEingabe_create();
extern Xv_opaque	o_popEingabe_controls2_create();
extern Xv_opaque	o_popEingabe_setAmZug_create();
extern Xv_opaque	o_popEingabe_setSetzModus_create();
extern Xv_opaque	o_popEingabe_butDrehen_create();
extern Xv_opaque	o_popEingabe_butSpiegeln_create();
extern Xv_opaque	o_popEingabe_butFuellen_create();
extern Xv_opaque	o_popEingabe_butGrund_create();
extern Xv_opaque	o_popEingabe_butEingabeOk_create();

typedef struct {
	Xv_opaque	popLaden;
	Xv_opaque	controls1;
	Xv_opaque	textLadenName;
	Xv_opaque	butSpielLaden;
} o_popLaden_objects;

extern o_popLaden_objects	*o_popLaden_objects_initialize();

extern Xv_opaque	o_popLaden_popLaden_create();
extern Xv_opaque	o_popLaden_controls1_create();
extern Xv_opaque	o_popLaden_textLadenName_create();
extern Xv_opaque	o_popLaden_butSpielLaden_create();

typedef struct {
	Xv_opaque	popSpeichern;
	Xv_opaque	controls5;
	Xv_opaque	textSpeichernName;
	Xv_opaque	butSpielSpeichern;
} o_popSpeichern_objects;

extern o_popSpeichern_objects	*o_popSpeichern_objects_initialize();

extern Xv_opaque	o_popSpeichern_popSpeichern_create();
extern Xv_opaque	o_popSpeichern_controls5_create();
extern Xv_opaque	o_popSpeichern_textSpeichernName_create();
extern Xv_opaque	o_popSpeichern_butSpielSpeichern_create();
#endif
