
-- PostgreSQL script part of the reversi program.
-- This script deletes and reloads the log generated by endgame_solver (exact_solver) when run with GAME_TREE_DEBUG option turned on.

-- Start psql by running: psql -U reversi -w -d reversi -h localhost
-- Load the file by running the command: \i pg_load_log.sql



DROP TABLE IF EXISTS es_log;

CREATE TABLE es_log (call_id INTEGER, hash VARCHAR(16), parent_hash VARCHAR(16), game_position VARCHAR(65), empty_count INTEGER, level INTEGER, PRIMARY KEY(call_id));

\COPY es_log FROM '/home/rcrr/base/prj/reversi/c/es_log.csv' WITH (FORMAT CSV, DELIMITER ';', HEADER true);

VACUUM (FULL, ANALYZE, VERBOSE) es_log;

SELECT COUNT(*) FROM es_log;



DROP TABLE IF EXISTS ifes_log;

CREATE TABLE ifes_log (call_id INTEGER, hash VARCHAR(16), game_position VARCHAR(65), empty_count INTEGER, PRIMARY KEY(call_id));

\COPY ifes_log FROM '/home/rcrr/base/prj/reversi/c/ifes_log.csv' WITH (FORMAT CSV, DELIMITER ';', HEADER true);

VACUUM (FULL, ANALYZE, VERBOSE) ifes_log;

SELECT COUNT(*) FROM ifes_log;
