--
-- 0106_up_cmp_cmq_cmr.sql
--
-- This file is part of the reversi program
-- http://github.com/rcrr/reversi
--
-- Author: Roberto Corradini mailto:rob_corradini@yahoo.it
-- Copyright 2018 Roberto Corradini. All rights reserved.
--
--
-- License:
--
-- This program is free software; you can redistribute it and/or modify it
-- under the terms of the GNU General Public License as published by the
-- Free Software Foundation; either version 3, or (at your option) any
-- later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA
-- or visit the site <http://www.gnu.org/licenses/>.
--
--
--
-- Adds structure to regab_prng_gp table to host the new rows having the best next
-- move played.
-- This doubles the solved positions for the empty_count = empty_count - 1. 
--

SET search_path TO reversi;

BEGIN;

-- Migration set-up
INSERT INTO migrations (migration_id, ins_time, label, description)
VALUES (0106, now(), 'cmp_cmq_cmr', 'adds structure to regab_prng_gp table to collect info for gp obtained playing the best move.');

--
-- The new field parent_gp_id could be NULL or has the reference to the parent game position.
--
ALTER TABLE regab_prng_gp ADD COLUMN parent_gp_id BIGINT DEFAULT NULL REFERENCES regab_prng_gp (seq) ON DELETE CASCADE;

--
-- Staus can take the following values:
--  - INS: Inserted.
--  - WIP: Selected for game_value calculation.
--  - CMP: game_value has been coputed and saved.
--  - CMQ: Marked for offspring generation.
--  - CMW: Selected anc locked for offspring generation.
--  - CMR: It is the offspring generated by a parent game position by playing the best move.
--  - CMS: Offspring has been generated.
--
ALTER TABLE regab_prng_gp ADD CONSTRAINT status_chk CHECK (status IN ('INS', 'WIP', 'CMP', 'CMQ', 'CMW', 'CMR', 'CMS'));

--
-- These indexes are needed to effectively delete records in regab_prng_gp.
--
CREATE INDEX regab_prng_gp_classification_gp_id_idx ON regab_prng_gp_classification (gp_id);
CREATE INDEX regab_prng_gp_parent_gp_id_idx ON regab_prng_gp (parent_gp_id);

-- End of migration
COMMIT;
