/**
 * @file
 *
 *
 * @todo [done] Remove every dependency on GamePosition and Board objects.
 *
 * @todo [done] Remove pass special case.
 *
 * @todo [done] Avoid malloc/free calls.
 *
 * @todo        Use the game_tree_utils stack.
 *
 * @todo [done] Use the most advanced Kogge-Stone routines.
 *
 * @todo        Transform the code from recursion to iteration.
 *
 * @todo [done] Refactor the logging system:
 *              - Remove the costly json generation.
 *              - Trasform logging from ASCI to binary.
 *                Write a postprocessor that generate the ASCI/csv from the binary file.
 *                Add the json generation to the postprocessor.
 *
 * @todo [done] Write a new hash algorithm that prepares the delta_hash between two game positions.
 *
 *
 * @brief Minimax solver module implementation.
 * @details It searches the end of the game for an exact outcome using the MINIMAX algorithm.
 *
 * @par minimax_solver.c
 * <tt>
 * This file is part of the reversi program
 * http://github.com/rcrr/reversi
 * </tt>
 * @author Roberto Corradini mailto:rob_corradini@yahoo.it
 * @copyright 2014, 2016 Roberto Corradini. All rights reserved.
 *
 * @par License
 * <tt>
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 3, or (at your option) any
 * later version.
 * \n
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * \n
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA
 * or visit the site <http://www.gnu.org/licenses/>.
 * </tt>
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <inttypes.h>

#include "game_tree_logger.h"
#include "minimax_solver.h"



/**
 * @cond
 */

/*
 * Prototypes for internal functions.
 */

static int
game_position_solve_impl (ExactSolution *const result,
                          Square *best_move,
                          const GamePositionX *const gpx,
                          GameTreeStack *const stack);



/*
 * Internal variables and constants.
 */

/* The logging environment structure. */
static LogEnv *log_env = NULL;

/* The predecessor-successor array of game position hash values. */
static uint64_t gpx_hash_stack[128];

/* The index of the last entry into gpx_hash_stack. */
static uint64_t *gpx_hash = gpx_hash_stack;

/* Flips generated by the move. The move is stored in position 0, at most ther are 19 flips. */
static Square flips[20];

/* Number of flips plus one. */
static int flip_count;

/* True when has has to be computed. */
static bool compute_hash = false;

/**
 * @endcond
 */



/**
 * @brief Solves the game position returning a new exact solution pointer.
 *
 * @param [in] root the starting game position to be solved
 * @param [in] env      parameter envelope
 * @return          a pointer to a new exact solution structure
 */
ExactSolution *
game_position_minimax_solve (const GamePositionX *const root,
                             const endgame_solver_env_t *const env)
{
  g_assert(root);
  g_assert(env);

  const GamePositionX ground = { .blacks = root->blacks, .whites = root->whites, .player = player_opponent(root->player) };
  *gpx_hash++ = game_position_x_hash(&ground);
  flips[0] = pass_move;
  flip_count = 1;

  log_env = game_tree_log_init(env->log_file);

  if (log_env->log_is_on) {
    game_tree_log_open_h(log_env);
    compute_hash = true;
  }

  int game_value = out_of_range_defeat_score;
  Square best_move = invalid_move;

  GameTreeStack *stack = game_tree_stack_new();

  game_tree_stack_init(root, stack);

  ExactSolution *result = exact_solution_new();
  exact_solution_set_solved_game_position_x(result, root);

  game_value = game_position_solve_impl(result, &best_move, root, stack);

  result->pv[0] = best_move;
  result->outcome = game_value;

  game_tree_stack_free(stack);

  game_tree_log_close(log_env);

  return result;
}



/**
 * @cond
 */

/*
 * Internal functions.
 */

static void
generate_move_array (int *move_count,
                     Square *moves,
                     SquareSet *move_set,
                     const GamePositionX *const gpx)
{
  Square *move = moves;
  *move_set = game_position_x_legal_moves(gpx);
  SquareSet remaining_moves = *move_set;
  if (!remaining_moves) {
    *move++ = pass_move;
  } else {
    while (remaining_moves) {
      const Square m = bit_works_bitscanLS1B_64_bsf(remaining_moves);
      *move++ = m;
      remaining_moves = bit_works_reset_lowest_bit_set_64_blsr(remaining_moves);
    }
  }
  *move_count = move - moves;
}

static bool
is_terminal_node (const GamePositionX *const current,
                  const SquareSet move_set)
{
  if (move_set) return false;
  const SquareSet empties = ~(current->blacks | current->whites);
  if (!empties) return true;
  GamePositionX next;
  game_position_x_pass(current, &next);
  const SquareSet next_legal_moves = game_position_x_legal_moves(&next);
  if (next_legal_moves) return false;
  return true;
}

static void
make_move (const GamePositionX *const current,
           const Square move,
           GamePositionX *const updated)
{
  flips[0] = move;
  flip_count = 1;
  if (move == pass_move) {
    game_position_x_pass(current, updated);
  } else {
    game_position_x_make_move(current, move, updated);
    if (compute_hash) {
      const SquareSet bitmove = 1ULL << move;
      const SquareSet cu_p = game_position_x_get_player(current);
      const SquareSet up_o = game_position_x_get_opponent(updated);
      SquareSet flip_set = up_o & ~(cu_p | bitmove);
      while (flip_set) {
        const Square f = bit_works_bitscanLS1B_64_bsf(flip_set);
        flip_set ^= 1ULL << f;
        flips[flip_count++] = f;
      }
    }
  }
}

static int
game_position_solve_impl (ExactSolution *const result,
                          Square *best_move,
                          const GamePositionX *const gpx,
                          GameTreeStack *const stack)
{
  Square *m;
  Square moves[32];
  Square child_best_move;
  int best_value, v;
  SquareSet move_set;
  int move_count;
  GamePositionX child_gpx;

  result->node_count++;

  generate_move_array(&move_count, moves, &move_set, gpx);

  if (compute_hash) {
    *gpx_hash = game_position_x_delta_hash(*(gpx_hash - 1), flips, flip_count, gpx->player);
    gpx_hash++;
  }

  if (log_env->log_is_on) {
    LogDataH log_data =
      { .sub_run_id   = game_tree_log_def_sub_run_id,
        .call_id      = result->node_count,
        .hash         = *(gpx_hash - 1),
        .parent_hash  = *(gpx_hash - 2),
        .blacks       = gpx->blacks,
        .whites       = gpx->whites,
        .player       = gpx->player,
        .json_doc     = NULL,
        .json_doc_len = 0,
        .call_level   = gpx_hash - gpx_hash_stack - 1 };
    game_tree_log_write_h(log_env, &log_data);
  }

  best_value = out_of_range_defeat_score;
  *best_move = invalid_move;

  if (is_terminal_node(gpx, move_set)) {
    result->leaf_count++;
    best_value = game_position_x_final_value(gpx);
    goto end;
  }

  for (m = moves; m - moves < move_count; m++) {
    make_move(gpx, *m, &child_gpx);
    v = - game_position_solve_impl(result, &child_best_move, &child_gpx, stack);
    if (v > best_value) {
      *best_move = *m;
      best_value = v;
    }
  }

 end:
  if (compute_hash) gpx_hash--;
  return best_value;
}

/**
 * @endcond
 */
