#
# rglmw.R
#
# Copyright (c) 2021 Roberto Corradini. All rights reserved.
#
# This file is part of the reversi program
# http://github.com/rcrr/reversi
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA
# or visit the site <http://www.gnu.org/licenses/>.
#
#
#
# This script implements 3 functions:
#
# load_dt_model_weights  : Returns a data.table with the data loaded from a POSITION model-weights CSV file.
# load_dtv_model_weights : The same as the previous one, but load the VALIDATION data.
#                          The two functions expect the data directory as data_dir parameter, where the RGLMDATA
#                          is stored, and the RUNCODE string (e.g. A2050) that identifies the RGLM regression.
# load_model_weights     : It is a wrapper to return the key info and the DATA PLOTS of the regression.
#
# The data processed by the functions is generated by rglm_batch.sh script.
#
# Usage:
#
# r <- load_model_weights("../rglmdata", "A2054")
# r$plot_distrib
#
# dtv <- load_dtv_model_weights("../rglmdata", "A2054")
# dtv_ordered <- dtv[order(abs(RESIDUAL),decreasing=TRUE),]
# dtvo <- dtv_ordered <- dtv[order(abs(RESIDUAL),decreasing=TRUE),]
#

library(ggplot2)
library(bit64)
library(data.table)
library(moments)

load_dt_model_weights <- function(data_dir, runcode) {
  data_file <- paste(data_dir, "/",runcode, "_01.w.P.csv", sep = "", collapse = NULL)
  dt  <- fread(data_file)
  return(dt)
}

load_dtv_model_weights <- function(data_dir, runcode) {
  validation_file <- paste(data_dir, "/",runcode, "_01.w.P_check.csv", sep = "", collapse = NULL)
  dtv <- fread(validation_file)
  return(dtv)
}

load_model_weights <- function(data_dir, runcode) {
  dt <- load_dt_model_weights(data_dir, runcode)
  dtv <- load_dtv_model_weights(data_dir, runcode)
  
  game_value_transformed_mean <- mean(dt$GAME_VALUE_TRANSFORMED)
  dt[, REFERENCE := GAME_VALUE_TRANSFORMED - game_value_transformed_mean]
  
  reference_den  <- density(dt$REFERENCE)
  residual_den   <- density(dt$RESIDUAL)
  validation_den <- density(dtv$RESIDUAL)
  
  reference_sd  <- sd(dt$REFERENCE)
  residual_sd   <- sd(dt$RESIDUAL)
  validation_sd <- sd(dtv$RESIDUAL)
  
  validation_mean <- mean(dtv$RESIDUAL)
  validation_min <- min(dtv$RESIDUAL)
  validation_max <- max(dtv$RESIDUAL)
  
  validation_skewness <- skewness(dtv$RESIDUAL)
  validation_kurtosis <- kurtosis(dtv$RESIDUAL)
  
  max_y <- max(max(reference_den$y), max(residual_den$y), max(validation_den$y))
  
  reference_color <- "slategray"
  residual_color  <- "firebrick"
  validation_color <- "black"
  
  reference_p0 <- geom_density(aes_string(x = dt$REFERENCE), color = reference_color)
  residual_p0 <- geom_density(aes_string(x = dt$RESIDUAL),  color = residual_color)
  validation_p0 <- geom_density(aes_string(x = dtv$RESIDUAL), color = validation_color)
  
  label_reference <- sprintf("Reference:\nsd = %6.4f", reference_sd)
  label_residual  <- sprintf("Residual:\nsd = %6.4f", residual_sd)
  label_validation <- sprintf("Validation:\nsd = %6.4f\nmean = %6.4f\nmin = %6.4f\nmax = %6.4f",
                              validation_sd, validation_mean,
                              validation_min, validation_max)
  
  p0 <- ggplot() + reference_p0 + residual_p0 + validation_p0 +
    labs(title = 'RGLM Residuals Distribution', subtitle = runcode) +
    xlab('Game value residual') + ylab('Probability density') +
    geom_vline(aes(xintercept = mean(dt$RESIDUAL)),
               color = validation_color, linetype="dashed", size=0.3) +
    geom_label(aes(x =  0.25, y = max_y * 0.60, label = label_reference),  color = reference_color , size = 3, hjust = 0) +
    geom_label(aes(x =  0.15, y = max_y * 0.90, label = label_residual),   color = residual_color  , size = 3, hjust = 0) +
    geom_label(aes(x = -0.45, y = max_y * 0.75, label = label_validation), color = validation_color, size = 3, hjust = 0) +
    theme_light() +
    theme(legend.position = "None")
  
  p1 <- ggplot() + geom_point(aes(x=jitter(dtv$EVALUATION_FUNCTION, amount=0.005), y=jitter(dtv$RESIDUAL, amount=0.005), alpha=I(0.04))) +
    labs(title = 'RGLM Residuals vs Fitted Values (evaluation function)', subtitle = runcode) +
    xlab('Game evaluation function') + ylab('Game value residual')
  
  p2 <- ggplot() + geom_point(aes(x=jitter(dtv$GAME_VALUE, amount=0.7), y=jitter(dtv$RESIDUAL, amount=0.005), alpha=I(0.02))) +
    labs(title = 'RGLM Residuals vs Game Values', subtitle = runcode) +
    xlab('Game value') + ylab('Game value residual')
  
  ret_val <- list(reference_sd=reference_sd,
                  residual_sd=residual_sd,
                  validation_sd=validation_sd,
                  validation_mean=validation_mean,
                  validation_skewness=validation_skewness,
                  validation_kurtosis=validation_kurtosis,
                  plot_distrib=p0,
                  plot_res_vs_fitted=p1,
                  plot_res_vs_gv=p2)
  return(ret_val)
}
